#!/usr/bin/env bash
# Build one markdown module index per relevant Effect package from the published npm tarball.
# The website API reference is generated from the same JSDoc, so the tarball's src/ is the
# version-pinned source of truth. Each index row: module, @since, one-line purpose (the
# module's top-of-file JSDoc, first paragraph), count of top-level export declarations.
#
# Usage: ./generate.sh [version]   (default: the version golf pins in its pnpm catalog)
set -euo pipefail
cd "$(dirname "$0")"
# golf's catalog pin: main checkout first, then the Effect worktree (where the migration lives).
VERSION="${1:-$(sed -nE "s/^  effect: ([0-9][^ ]*)$/\1/p" \
  "$HOME/repos/bokendell/golf/pnpm-workspace.yaml" \
  "$HOME/repos/bokendell/golf/.worktrees/effect/pnpm-workspace.yaml" 2>/dev/null | head -1)}"
[ -n "$VERSION" ] || { echo "pass a version (could not read golf's effect pin)"; exit 1; }
PKGS=(effect @effect/vitest @effect/platform-node @effect/platform-node-shared @effect/opentelemetry
  @effect/sql-pg @effect/ai-anthropic @effect/ai-openai @effect/ai-openrouter @effect/ai-openai-compat
  @effect/atom-react @effect/openapi-generator)
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
for pkg in "${PKGS[@]}"; do
  dir="$tmp/$(echo "$pkg" | tr '/@' '__')"; mkdir -p "$dir"
  tgz=$(cd "$dir" && npm pack "$pkg@$VERSION" --silent --registry=https://registry.npmjs.org)
  tar -xzf "$dir/$tgz" -C "$dir"
  python3 - "$pkg" "$VERSION" "$dir/package" <<'PY'
import os, re, sys
pkg, ver, root = sys.argv[1:4]
src = os.path.join(root, "src")
rows = []
for d, dirs, files in os.walk(src):
    dirs[:] = sorted(x for x in dirs if x != "internal")
    for f in sorted(files):
        if not f.endswith(".ts") or f.endswith(".d.ts") or f == "index.ts":
            continue
        path = os.path.join(d, f)
        text = open(path, encoding="utf-8").read()
        m = re.match(r"\s*(?:#![^\n]*\n\s*)?/\*\*(.*?)\*/", text, re.S)
        doc = m.group(1) if m else ""
        lines = [re.sub(r"^\s*\* ?", "", l) for l in doc.splitlines()]
        para, since = [], ""
        for l in lines:
            if l.startswith("@since"):
                since = l.split(None, 1)[1].strip() if " " in l else ""
        for l in lines:
            if l.startswith("@") or (not l.strip() and para):
                break
            if l.strip():
                para.append(l.strip())
        summary = " ".join(para).replace("|", "\\|")
        if len(summary) > 220:
            cut = summary[:220]
            summary = (cut[: cut.rfind(". ") + 1] if ". " in cut else cut.rsplit(" ", 1)[0] + " …")
        n = len(re.findall(r"^export (?:declare )?(?:abstract )?(?:const|let|function\*?|class|interface|type|namespace|enum)\b", text, re.M))
        mod = os.path.relpath(path, src)[:-3]
        rows.append((mod, since, summary or "(no module doc)", n))
out = pkg.replace("@effect/", "") + ".md"
with open(out, "w") as fh:
    fh.write(f"# `{pkg}` @ {ver} — module index\n\n")
    fh.write(f"Generated by `generate.sh` from the npm tarball's `src/` (top-of-file JSDoc). {len(rows)} modules.\n")
    fh.write("Exports = top-level `export` declarations in the module file (re-exports not counted).\n\n")
    fh.write("| Module | Since | Purpose | Exports |\n|---|---|---|---|\n")
    for mod, since, s, n in rows:
        fh.write(f"| `{mod}` | {since} | {s} | {n} |\n")
print(f"{pkg}: {len(rows)} modules -> {out}")
PY
done
